# Generated by Django 5.0.6 on 2024-06-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('cont', models.TextField()),
                ('category', models.ManyToManyField(to='Bhood.cate')),
            ],
        ),
        migrations.AddField(
            model_name='cate',
            name='category',
            field=models.ManyToManyField(to='Bhood.post'),
        ),
    ]
