# Generated by Django 5.0.6 on 2024-06-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bhood', '0002_cate_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cate',
            name='category',
            field=models.ManyToManyField(blank=True, to='Bhood.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, to='Bhood.cate'),
        ),
    ]
