# Generated by Django 5.0.6 on 2024-06-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bhood', '0006_post_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
    ]
