# Generated by Django 5.0.6 on 2024-07-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bhood', '0010_alter_messenger_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(blank=True, upload_to='photos_of_profile/%Y/%m/%d/')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
