# Generated by Django 5.0.6 on 2024-07-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bhood', '0012_alter_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predlozka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('cont', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('category', models.ManyToManyField(blank=True, to='Bhood.cate')),
            ],
        ),
    ]
