# Generated by Django 5.0.6 on 2024-07-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bhood', '0018_alter_post_options_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='photos_of_profile/%Y/%m/%d/'),
        ),
    ]
