# Generated by Django 5.0.6 on 2024-07-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bhood', '0020_ratepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratepost',
            name='rate',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ratepost',
            name='rate_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
