# Generated by Django 5.0.6 on 2024-07-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bhood', '0023_alter_ratepost_rate_alter_ratepost_rate_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratepost',
            name='rate_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
