# Generated by Django 5.0.6 on 2024-07-18 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bhood', '0026_ratepost_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratepost',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Bhood.profile'),
        ),
    ]
