# Generated by Django 5.0.6 on 2024-07-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bhood', '0027_alter_ratepost_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratepost',
            name='rated',
            field=models.BooleanField(default=False),
        ),
    ]
