# Generated by Django 5.0.6 on 2024-07-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bhood', '0028_ratepost_rated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(blank=True),
        ),
    ]
