# Generated by Django 5.0.6 on 2024-07-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bhood', '0030_alter_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratepost',
            name='rate',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')]),
        ),
    ]
