# Generated by Django 5.0.6 on 2024-07-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bhood', '0031_alter_ratepost_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
